In [10]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:85% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:12pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:12pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:12px;}
</style>
"""))

<font size ='5' color='black'>ch.09 파일 입출력 프로그래밍</font>
- 파일 : txt,  pickle(머신러닝 모델 저장, 넘파이 배열 저장), csv, json, h5(딥러닝 모델 저장)

# 1. txt 파일 입출력

* 작업 종류
    - w : 기존의 파일이 있는 경우 덮어쓰기. 없을 경우 파일 생성.
    - a : 기존 내용을 보존, 파일의 맨 끝에 내용을 이어 붙임. 없을 경우 파일 생성.
    - r : 기본값, 파일을 읽기만 할 때 사용. 없을 경우 FileNotFoundError 에러 발생.
    - x : 파일을 새로 만들어 쓰기 모드로 생성. 기존의 파일이 있는 경우 FileExistsError 에러 발생.

* 파일 형식 지정 - t : 텍스트 모드, 기본값 (.txt, .csv)

## 1.1 txt - write

In [12]:
f = open('data/ch09.txt', 'w', encoding='utf-8')
# 상대경로 : 코드파일 기준으로 작성 / 절대경로 : 드라이브 위치부터 작성
print("쓰기 가능한지 : ", f.writable())

쓰기 가능한지 :  True

In [13]:
f.write('Hello\nWorld\n') 
f.close() # close 없을 시 출력 구문 저장 불가

In [14]:
# with 구문을 사용 시 close 불필요
with open('data/ch09.txt', 'a') as f: # 파일을 'a' 모드로 열기
    f.write('Python is easy\nPython is smart.\n')

In [16]:
with open('data/ch09.txt', 'a') as f: # 파일을 'a' 모드로 열기
    print('프린트 함수를 사용한 파일 쓰기\n', file = f) # print() 함수의 end는 \n가 기본값으로 포함됨.
# jupyter notebook에서는 utf-8 방식으로 한글 인코딩되어 cp949 파일을 확인할 수 없음

- utf-8/UTF-8/UTF8 : 한글 조합형 - 주피터 노트북의 한글 인코딩 기본값
- euc-kr : 한글 완성형 (믜,꺓, ... 작성불가)
- cp949 : 한글 확장완성형 (믜,꺓, ... 작성가능) ; open()함수의 기본 인코딩 방식

In [18]:
# 파일을 만들어 쓰기 모드로 열기

with open('data/ch09.txt', 'w', encoding='utf-8') as f:
    # 방법 1
    f.write('홍길동,30,서울\n김길동,25,안양\n')
    # or
    f.write('홍길동,30,서울\n')
    f.write('김길동,25,안양\n')
    # 방법 2
    text_list = ['홍길동,30,서울\n', '김길동,25,안양\n']
    for line in text_list:
        f.write(line)
    # 방법 3
    f.writelines(text_list)

## 1.2 txt - read

In [19]:
# 방법 1 : 파일을 한번에 읽고 출력하기

with open('data/ch09.txt', 'r', encoding='utf-8') as txtf:
    filecontent = txtf.read()
print(filecontent)

홍길동,30,서울
김길동,25,안양
홍길동,30,서울
김길동,25,안양
홍길동,30,서울
김길동,25,안양
홍길동,30,서울
김길동,25,안양

In [22]:
# 방법 2 : 파일을 한 줄씩 읽고 출력하기

with open('data/ch09.txt', 'rt', encoding='utf-8') as txtf:
    filecontent = txtf.readline() # 한 줄 읽기    
print(filecontent)

홍길동,30,서울

['김길동,25,안양\n', '홍길동,30,서울\n', '김길동,25,안양\n', '홍길동,30,서울\n', '김길동,25,안양\n', '홍길동,30,서울\n', '김길동,25,안양\n']

In [23]:
# 방법 2-1 : 파일을 한 줄씩 읽으며 전체 내용 출력하기
with open('data/ch09.txt', 'rt', encoding='utf-8') as txtf:
    filecontent = txtf.readline() # 한 줄(현재 커서 위치부터 \n까지) 읽기
    while line!= '' : # line이 빈 스트링['']이 아닐 경우 아래 명령어 실행
        print(line, end='')
        line = txtf.readline() # 마지막 line을 참조한 이후 더 이상 내용이 없으면 ''을 반환

김길동,25,안양
김길동,25,안양
홍길동,30,서울
김길동,25,안양
홍길동,30,서울
김길동,25,안양
홍길동,30,서울
김길동,25,안양

In [25]:
# 방법 3 : 파일을 한번에 읽어 list로 받아 출력하기
with open('data/ch09.txt', 'r', encoding='utf-8') as txtf:
    lines = txtf.readlines() # 파일 전체를 한 줄씩 읽기

for line in lines:
    print(line, end='')

홍길동,30,서울
김길동,25,안양
홍길동,30,서울
김길동,25,안양
홍길동,30,서울
김길동,25,안양
홍길동,30,서울
김길동,25,안양

# 2. pickle 객체 입출력

## 2.1 형식이 있는 텍스트 데이터 불러오기
- ch09_member.txt → 객체 리스트 변환

In [59]:
with open('data/ch09_member.txt', 'rt', encoding='utf-8') as f:
    lines = f.readlines()
    
for line in lines:
    data = line.strip().split(', ') # strip() : space, enter, tab 등을 제거함
    name = data[0]
    age = int(data[1])
    email = data[2]
    address = data[3]
    print("이름 : {}, 나이 : {}, 이메일 : {}, 주소 : {}".format(name, age, email, address))

이름 : 홍길동, 나이 : 20, 이메일 : kildong@hong.com, 주소 : 서울시 관악구
이름 : 홍길숙, 나이 : 25, 이메일 : kilsuk1@hong.com, 주소 : 서울시 영등포구
이름 : 신길동, 나이 : 30, 이메일 : shinkil@hong.com, 주소 : 서울시 동작구

In [64]:
class Member:
    def __init__(self, name, age, email, address):
        self.name = name
        self.age = age
        self.email = email
        self. address = address
        
    def __eq__(self, other):
        if isinstance(other, Member):
            return self.__str__() == other.__str__() # a == b 사용 시, a.__eq__(b)가 호출됨.
        return False
    
    def __str__(self):
        return f"{self.name}, {self.age}, {self.email}, {self.address}"
    
#    def as_dict(self): # 객체를 딕셔너리로 반환
#        return {'name':self.name, 'age':self.age, 'email':self.email, 'address':self.address}
    
    def as_list(self): # 객체를 리스트로 반환
        return [self.name, self.age, self.email, self.address]

In [61]:
member = Member("홍길동","33","hongil@h.co.kr","신림동")
print(member)

홍길동, 33, hongil@h.co.kr, 신림동

In [65]:
member = Member("홍길동","33","hongil@h.co.kr","신림동")
member2 = Member("홍길동","33","hongil@h.co.kr","신림동")
print(id(member), id(member2))
print(member==member2)
print(member.__eq__(member2))
print(member.__dict__)
print(member.as_list())

3117680894944 3117692365952
True
True
{'name': '홍길동', 'age': '33', 'email': 'hongil@h.co.kr', 'address': '신림동'}
['홍길동', '33', 'hongil@h.co.kr', '신림동']

In [66]:
# 파일의 내용을 member list나 dict list로 만들기

member_list=[] # 파일의 내용이 member 객체로 추가될 빈 리스트
member_dict_list = []

with open('data/ch09_member.txt', 'rt', encoding='utf-8') as f:
    lines = f.readlines()
    
for line in lines:
    data = line.strip().split(',') # strip() : space, enter, tab 등을 제거함
    name = data[0].strip()
    age = int(data[1].strip())
    email = data[2].strip()
    address = data[3].strip()
    member = Member(name, age, email, address)
    member_list.append(member)
    member_dict_list.append(member.__dict__)

In [67]:
[member.__str__() for member in member_dict_list]

["{'name': '홍길동', 'age': 20, 'email': 'kildong@hong.com', 'address': '서울시 관악구'}",
 "{'name': '홍길숙', 'age': 25, 'email': 'kilsuk1@hong.com', 'address': '서울시 영등포구'}",
 "{'name': '신길동', 'age': 30, 'email': 'shinkil@hong.com', 'address': '서울시 동작구'}"]

## 2.2 피클링
- member_list → 피클 파일에 쓰기
- 피클 파일을 읽기 → loaded_member_list
- 파일 형식 지정 - b : 바이너리 모드 (.pkl)


- 문법
   - 피클링
   `pickle.dump(저장하고 싶은 객체, 피클링할 파일 객체)`
   - 언피클링
   `pickle.load(객체로 불러올 피클링 파일)`

In [68]:
# 피클링(확장자: pkl, pickle, data)을 이용하여 객체를 파일에 저장하기

import pickle
with open('data/ch09_member.pkl', 'wb') as f:
    pickle.dump(member_list, f)

In [69]:
# 피클링을 이용하여 파일에서 객체 데이터 읽기

with open('data/ch09_member.pkl', 'rb') as f:
    loaded_member_list = pickle.load(f)

In [70]:
# member_list와 loaded_member_list 비교
for member, loaded_member in zip(member_list, loaded_member_list):
    print(member,'/',loaded_member,sep='')

홍길동, 20, kildong@hong.com, 서울시 관악구/홍길동, 20, kildong@hong.com, 서울시 관악구
홍길숙, 25, kilsuk1@hong.com, 서울시 영등포구/홍길숙, 25, kilsuk1@hong.com, 서울시 영등포구
신길동, 30, shinkil@hong.com, 서울시 동작구/신길동, 30, shinkil@hong.com, 서울시 동작구

In [72]:
# member_list와 loaded_member_list 비교 2 (__eq__ 처리 이후)
for member, loaded_member in zip(member_list, loaded_member_list):
    print(member == loaded_member)

True
True
True

# 3. csv 파일 입출력
- csv 파일의 자료를 list 또는 dict 데이터로 읽고 쓰기
- csv 파일의 자료를 데이터 프레임으로 읽고 쓰기 (11장)

## 3.1 reader
- 데이터 양옆의 쌍따옴표("")와 행 끝에 있는 줄바꿈 문자(\n)를 걸러냄.
- 쉼표(,)를 기준으로 글자들을 쪼개서 파이썬의 list로 변환.

In [8]:
import csv
with open('data/ch09_member1.csv', 'r', encoding='utf-8') as f:
    reader = csv.reader(f) # f를 통해 파일과 연결 후, reader를 통해 CSV 형식을 list로 변환
    for row in reader:
        print(row)

['홍길동', '20', 'kildong@hong.com', '서울시 관악구']
['김길동', '40', 'kimdong@hong.com', '서울시 영등포구']
['신길동', '30', 'sindong@hong.com', '서울시 동작구']

In [11]:
with open('data/ch09_member1-cp.csv') as f:
    reader = csv.reader(f)
for row in reader: # with 구문을 벗어나 파일이 닫힘.
    print(row)

ValueError: I/O operation on closed file.

In [12]:
with open('data/ch09_member1-cp.csv') as f:
    reader = csv.reader(f)
    for row in reader:
        print(row)

['홍길동', '20', 'kildong@hong.com', '서울시 관악구', '']
['김길동', '40', 'kimdong@hong.com', '서울시 영등포구', '팀장']
['신길동', '30', 'sindong@hong.com', '서울시 동작구', '']

In [14]:
with open('data/ch09_member1-cp.csv') as f:
    reader = csv.reader(f)
    result = list(reader) # 파일이 닫히기 전, result에 list 작성
for row in result: # list를 가져왔기 때문에 파일 상태와 관계 없이 for문 구동 가능
    print(row)

['홍길동', '20', 'kildong@hong.com', '서울시 관악구', '']
['김길동', '40', 'kimdong@hong.com', '서울시 영등포구', '팀장']
['신길동', '30', 'sindong@hong.com', '서울시 동작구', '']

In [19]:
# quoting : CSV 파일의 따옴표 처리 정책을 정하는 역할. 기본값 - QUOTE_MINIMAL
# QUOTE_NONNUMERIC : 파일에서 따옴표가 없는 데이터를 발견하면 실수형 숫자로 변환(float()으로, 문자형 입력 시 에러)
import csv
with open('data/ch09_member1.csv', 'r', encoding='utf-8') as f:
    reader = csv.reader(f, quoting=csv.QUOTE_NONNUMERIC)
    
    for row in reader:
        print(row)

['홍길동', 20.0, 'kildong@hong.com', '서울시 관악구']
['김길동', 40.0, 'kimdong@hong.com', '서울시 영등포구']
['신길동', 30.0, 'sindong@hong.com', '서울시 동작구']

## 3.2 writer
- 파일에 구분자로 연결된 문자열 데이터를 저장하는 객체를 반환

In [20]:
user_list = [['홍길동', 20, 'kildong@hong.com', '서울시 관악구'],
            ['김길동', 40, 'kimdong@hong.com', '서울시 영등포구'],
            ['신길동', 30, 'sindong@hong.com', '서울시 동작구']]

In [22]:
with open('data/ch09_member2_write_cp.csv', 'w') as f:
    writer = csv.writer(f) # f를 통해 파일과 연결 후, writer를 통해 CSV 문법에 맞춰 텍스트 변환
    for user in user_list:
        writer.writerow(user) # 한 줄씩 쓰기

In [24]:
with open('data/ch09_member2_write_cp.csv', 'w', newline='') as f:
                                        # newline='' : 엑셀 상의 줄바꿈 중복 방지
    writer = csv.writer(f)
    writer.writerows(user_list) # 한번에 쓰기

## 3.3 DictReader
- csv 파일 헤더의 제목을 Key로, 데이터들을 Value로 매칭하여 딕셔너리(dict) 형태로 한 줄씩 반환

In [28]:
with open('data/ch09_member3.csv', 'r', encoding='utf-8') as f:
    dict_reader = csv.DictReader(f) # 결측치 표기 - 기본값 : None
    result = list(dict_reader)
result

[{'name': '홍길동',
  'age': '20',
  'email': 'h@h.com',
  'address': '서울시 관악구',
  'job': None},
 {'name': '신길동',
  'age': '40',
  'email': 's@h.com',
  'address': '서울시 영등포구',
  'job': '팀장'},
 {'name': '김길동',
  'age': '30',
  'email': 'k@h.com',
  'address': '서울시 동작구',
  'job': None}]

In [29]:
with open('data/ch09_member3.csv', 'r', encoding='utf-8') as f:
    dict_reader = csv.DictReader(f, restval='-') # 결측치 표기 restval='-' - 기본값 : None
    result = list(dict_reader)
result

[{'name': '홍길동',
  'age': '20',
  'email': 'h@h.com',
  'address': '서울시 관악구',
  'job': '-'},
 {'name': '신길동',
  'age': '40',
  'email': 's@h.com',
  'address': '서울시 영등포구',
  'job': '팀장'},
 {'name': '김길동',
  'age': '30',
  'email': 'k@h.com',
  'address': '서울시 동작구',
  'job': '-'}]

In [30]:
import pandas as pd
pd.read_csv('data/ch09_member3.csv') # 11장 데이터 프레임

  name  age    email   address  job
0  홍길동   20  h@h.com   서울시 관악구  NaN
1  신길동   40  s@h.com  서울시 영등포구   팀장
2  김길동   30  k@h.com   서울시 동작구  NaN

In [35]:
# 헤더가 없는 csv 파일을 딕셔너리로 변환하기
with open('data/ch09_member1-cp.csv', 'r') as f:
    dict_reader = csv.DictReader(f, fieldnames=['이름', '나이', '이메일', '주소', '직책'])
    # fieldnames=[] 헤더가 없는 파일의 키를 넣어줌
    for row in dict_reader:
        print(row)

{'이름': '홍길동', '나이': '20', '이메일': 'kildong@hong.com', '주소': '서울시 관악구', '직책': ''}
{'이름': '김길동', '나이': '40', '이메일': 'kimdong@hong.com', '주소': '서울시 영등포구', '직책': '팀장'}
{'이름': '신길동', '나이': '30', '이메일': 'sindong@hong.com', '주소': '서울시 동작구', '직책': ''}

In [36]:
with open('data/ch09_member1.csv', 'r', encoding='utf-8') as f:
    dict_reader = csv.DictReader(f, fieldnames=['name','age','email','address'])
    result = list(dict_reader)
for row in result:
    print(row)

{'name': '홍길동', 'age': '20', 'email': 'kildong@hong.com', 'address': '서울시 관악구'}
{'name': '김길동', 'age': '40', 'email': 'kimdong@hong.com', 'address': '서울시 영등포구'}
{'name': '신길동', 'age': '30', 'email': 'sindong@hong.com', 'address': '서울시 동작구'}

## 3.4 DictWriter
- 파이썬의 딕셔너리(dict) 데이터를 CSV 파일로 저장

In [37]:
fieldname = list(result[0].keys())
fieldname

['name', 'age', 'email', 'address']

In [41]:
with open('data/ch09_member4.csv', 'w', encoding='utf-8', newline='') as f:
    dict_writer = csv.DictWriter(f, fieldnames=fieldname)
    # f를 통해 파일과 연결 후, fieldnames에 지정된 Key 순서에 맞춰 CSV 형식으로 저장
    dict_writer.writeheader() # 헤더 설정
    dict_writer.writerows(result)

# 4. json 파일 입출력

## 4.1 json dump
- 딕셔너리 리스트 데이터를 json 파일로 저장
- 객체 리스트 데이터를 json 파일로 저장
* 성질: 파이썬 객체를 변환함과 동시에 오픈된 파일 객체(f)에 즉시 기록
* 매개변수: dump(데이터, 파일객체)

In [35]:
data = [{'name': '홍길동','age': '20','email': 'h@h.com','address': '서울시 관악구','job': '-'},
     {'name': '신길동','age': '40','email': 's@h.com','address': '서울시 영등포구','job': '팀장'},
     {'name': '김길동','age': '30','email': 'k@h.com','address': '서울시 동작구','job': '-'}]

- json 파일로 저장 시 데이터가 한글일 경우
```
    - ensure_ascii : 비영어권 문자들을 어떻게 처리할지 결정.
    - True : 기본값, 모든 출력을 ASCII(미국 표준 코드) 문자로만 안전하게 표현.
             ASCII 범위(영어, 숫자, 키보드 특수문자)를 벗어나는 한글이나 이모지 같은 문자들을 
             전부 아스키 형태의 유니코드 이스케이프 형태(\uXXXX)로 강제 변환해서 저장.
    - False :  ASCII 범위(영어, 숫자, 키보드 특수문자)를 벗어나는 한글이나 이모지 같은 문자들을 그대로 저장
```

### 딕셔너리 리스트를 json 파일로 저장 시

In [36]:
import json
with open('data/ch09_member1.json', 'w', encoding='utf-8') as jsonf:
    json.dump(data, jsonf, ensure_ascii=False)

In [37]:
import json
with open('data/ch09_member1.json', 'w', encoding='utf-8') as jsonf:
    json.dump(data, jsonf, ensure_ascii=False, indent=' ')
                                        # indent : json 파일 저장 시 들여쓰기 사용

### 객체 리스트를 json 파일로 저장 시

In [38]:
 
class Member:
    def __init__(self, name, age, email, address):
        self.name = name
        self.age = age
        self.email = email
        self.address = address
    def as_dict(self):
        '객체를 딕셔너리로 바꾸어 반환, json.dump 사용 시 필요'
        return self.__dict__
    def __str__(self):
        return f'이름 :{self.name}, 나이 :{self.age}, 이메일 :{self.email}, 주소 :{self.address}'
    def __eq__(self, other):
        if isinstance(other, Member): # other가 Member class일 경우, return
            return self.__str__() == other.__str__()
        else:
            return False

In [39]:
member1 = Member('홍길동',20,'h@h.com','관악구')
member2 = Member('홍길동',20,'h@h.com','관악구')
print(member1 == member2) # a == b 실행 시 a.__eq__(b) 호출.
print(member1.__eq__("홍길동"))

True
False

In [40]:
member_list = [Member('홍길동',20,'h1@h.com','신대방'),
              Member('김길동',30,'h2@h.com','봉천'),
              Member('신길숙',25,'h3@h.com','신림')]
for member in member_list:
    print(member)

이름 :홍길동, 나이 :20, 이메일 :h1@h.com, 주소 :신대방
이름 :김길동, 나이 :30, 이메일 :h2@h.com, 주소 :봉천
이름 :신길숙, 나이 :25, 이메일 :h3@h.com, 주소 :신림

In [41]:
# default : JSON으로 변환할 수 없는 객체를 만났을 때, 이를 어떻게 처리할지 알려줌. 함수 지정 가능.
with open('data/ch09_member2.json', 'w', encoding='utf-8') as jsonf:
    json.dump(member_list, jsonf, ensure_ascii=False, indent=' ', 
              default=Member.as_dict) # 객체를 딕셔너리 형태로 반환하는 인스턴스 함수 지정

## 4.2 json load
- json 파일을 딕셔너리 리스트 변수로 읽기
- json 파일을 객체 리스트 변수로 읽기

### json 파일을 딕셔너리 리스트로 읽기

In [42]:
with open('data/ch09_member1.json', 'r', encoding='utf-8') as jsonf:
    load_data = json.load(jsonf)

In [43]:
result = set() # 두 딕셔너리의 item이 같은지 item마다 T/F
for d, load_d in zip(data, load_data):
    result.add(d==load_d)
    
result

{True}

### json 파일을 객체 리스트로 읽기

In [46]:
def as_member(dic):
    '딕셔너리 데이터를 매개변수로 받아 Member 객체로 반환하는 함수'
    return Member(dic.get('name'), dic.get('age'), dic.get('email'), dic.get('address'))

In [47]:
m = as_member({'name':'kim', 'age':24, 'email':'234@asd.df','address':'seoul'})
print(m) # as_member 테스트용

이름 :kim, 나이 :24, 이메일 :234@asd.df, 주소 :seoul

In [23]:
with open('data/ch09_member2.json', 'r', encoding='utf-8') as jsonf:
    load_member_list = json.load(jsonf, object_hook=as_member)
           # object_hook = 읽어온 딕셔너리를 내가 만든 파이썬 클래스 객체로 변환

In [26]:
type(load_member_list[0])

__main__.Member

In [28]:
result = []
for member, load_member in zip(member_list, load_member_list):
    result.append(member==load_member)
    
all(result)

True

# 5. hdf5/h5 파일 입출력
- 딥러닝 모델 저장 용도(확장자 : h5, keras)
- 데이터 프레임 입출력

In [30]:
import seaborn as sns # 데이터 시각화 모듈
iris_df = sns.load_dataset("iris")
iris_df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

### h5 파일 쓰기
- 데이터 프레임을 h5(hdf/hdf5)파일로 저장하기

In [32]:
iris_df.to_hdf('data/ch09_iris.h5', key='iris')

### h5 파일 읽기
- h5(hdf/hdf5)파일을 데이터 프레임로 불러오기

In [38]:
import pandas as pd
load_iris_df = pd.read_hdf('data/ch09_iris.h5', key='iris')
load_iris_df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [36]:
all(iris_df == load_iris_df)

True

# 연습문제

## 실습형

- 프로그램 시작 시:
    * 파일이 있으면 파일 input -> customer_list(Customer class의 객체 list)
    * 파일이 없으면 빈 파일 생성
- ch09_custeomers.txt 파일 내용:
```
홍길동, 010-9999-9999, k@hong.com, 30, 5, vvip
유길동, 010-5432-2222, y@hong.com, 20, 2, 가칠해
```

### Customer class 작성
    * Customer("홍길동", "010-9999-9999", "k@hong.com", 30, 5, "vvip")
    * __init__, __str__, as_dict, to_txt_style(객체를 txt 파일로 출력)

In [10]:
class Customer:
    def __init__(self, name, phone, email, age, grade, etc):
        self.name  = name
        self.phone = phone
        self.email = email
        self.age   = age
        self.grade = grade
        self.etc   = etc
    def as_dict(self):
        return self.__dict__
    
    def __str__(self): # ***  홍길동    010-9999-9999  k@k.com   30   vvip
        return "{:>6}\t{:>5}\t{:15}\t{:^20}\t\t{:>3}\t{}".format(self.grade*'*',
                                                           self.name, 
                                                           self.phone,
                                                           self.email,
                                                           self.age,
                                                           self.etc)
    
    def to_text_style(self): # 홍길동, 010-9999-9999, k@hong.com, 30, 5, vvip
        return "{}, {}, {}, {}, {}, {}".format(self.name, 
                                              self.phone,
                                              self.email,
                                              self.age,
                                              self.grade,
                                              self.etc)

In [3]:
def to_customer(row):
    data = row.strip().split(', ')
    name = data[0]
    phone = data[1]
    email = data[2]
    age   = int(data[3])
    grade = int(data[4])
    etc   = data[5]
    return Customer(name, phone, email, age, grade, etc)

### 첫 실행 시
```
data/ch09_custeomers.txt의 내용을 customer_list에 입력받고 customer_list를 return
data/ch09_custeomers.txt 빈 파일 생성하고 customer_list=[], customer_list를 return
```

In [4]:
def load_customers():
    customer_list = []
    try:
        with open('data/ch09_customers.txt', 'r', encoding='utf-8') as f:
            lines = f.readlines()
            for line in lines:
                customer = to_customer(line)
                customer_list.append(customer)
    except FileNotFoundError:
        print("데이터 파일 ch09_customers.txt는 존재하지 않는 파일입니다. 파일을 생성합니다.")
        with open('data/ch09_customers.txt', 'w', encoding='utf-8') as f:
            f.write('')
    
    return customer_list

### 정보 입력

In [5]:
def fn1_insert_customer_info():
    import re
    
    name = input('이름 : ')
    name_pattern = r'[가-힣]{2,}'
    while not re.search(name_pattern, name):
        print('알 수 없는 이름입니다.')
        name = input('이름 : ')

    phone = input('전화번호 : ')
    tel_pattern = r"[0]\d{1,2}[\-)\s\.]\d{3,4}[\-)\s\.]\d{4}"
    while not re.search(tel_pattern, phone):
        print('올바른 전화번호 형식이 아닙니다. -를 포함하여 입력하세요.')
        phone = input('전화번호 : ')   

    email = input('이메일 : ')
    email_pattern = r"(\w+)@(\w+\.\w+\.?\w+)"
    while not re.search(email_pattern, email):
        print('올바른 이메일 형식이 아닙니다.')
        email = input('이메일 : ') 

    while True:
        try:
            age = int(input('나이 : '))
            if (age<=0)|(130<age):
                raise Exception('잘못된 입력입니다.')
            break
        except:
            print("올바른 나이를 입력하세요")
            
    try:
        grade = int(input('고객등급 : '))
        if grade<1:
            grade = 1
            print("1 등급으로 입력됩니다.",)
        if grade>5:
            grade = 5
            print("5 등급으로 입력됩니다.")
    except:
        grade = 1
        print("올바른 등급을 입력하지 않을 시 1 등급으로 입력됩니다.")
        
    etc = input('etc : ')
    print()
    return Customer(name, phone, email, age, grade, etc)

### 정보 조회

In [18]:
def fn2_print_customers(customer_list):
    print("="*100)
    print("{:^100}".format('고객정보'))
    print("-"*100)
    print("{:>5}{:>4}\t{:^25}\t{:15}\t{:>3}\t{}".format('고객등급',
                                                          '이름', 
                                                          '전화번호',
                                                          '이메일',
                                                          '나이',
                                                          '기타'))
    print("-"*100)
    for customer in customer_list:
        print(customer)

### 실행 종료

In [7]:
def fn3_save_customer_txt(customer_list):
    customer_text_list = []
    for customer in customer_list:
        text = customer.to_text_style()+'\n'
        customer_text_list.append(text)
    with open('data/ch09_customers.txt', 'w', encoding='utf-8') as f:
        f.writelines(customer_text_list)
    print('백업 완료, 프로그램을 종료합니다.')

In [8]:
def main():
    global customer_list
    customer_list = load_customers()
    while True:
        try:
            while True:
                print("1:입력", "2:전체 출력", "3:데이터 백업 후 종료 ", sep=' | ', end='')
                fn = int(input('* 메뉴 선택 : '))
                if fn == 1:
                    customer = fn1_insert_customer_info()
                    customer_list.append(customer)
                if fn == 2:
                    fn2_print_customers(customer_list)
                if fn == 3:
                    fn3_save_customer_txt(customer_list)
                    break
            break
        except:
            print('다시 입력하세요.')

In [19]:
if __name__ == '__main__':
    main()

1:입력 | 2:전체 출력 | 3:데이터 백업 후 종료 * 메뉴 선택 : 2
====================================================================================================
                                                고객정보
----------------------------------------------------------------------------------------------------
 고객등급  이름	          전화번호           	이메일            	 나이	기타
----------------------------------------------------------------------------------------------------
 *****	  홍길동	010-9999-9999  	     k@hong.com     		 30	vvip
    **	  유길동	010-5432-2222  	     y@hong.com     		 20	가칠해
   ***	  신림동	010-8888-8888  	     s@song.com     		 33	글쎄
  ****	  홍길동	010-7777-7777  	     h@hong.com     		 33	vip
  ****	  홍길동	010-9999-9999  	    hong@h.co.kr    		 32	동해번쩍
  ****	  김길동	010-8888-8888  	    kim@k.co.kr     		 33	서해번쩍
     *	 최종수정	010-1234-4312  	   last@test.com    		 24	진짜 최종
 *****	  찐최종	010-9999-9999  	  realast@real.com  		 99	진짜마지막
1:입력 | 2:전체 출력 | 3:데이터 백업 후 종료 * 메뉴 선택 : 3
백업 완료, 프로그램을 종료합니다.

## 문제풀이형

In [1]:
#1 -  3
#2 - 4
#3 - 1