In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:85% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:12pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:12pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:12px;}
</style>
"""))

<font size ='5' color='black'>ch.11 데이터프레임과 시리즈</font>
- pip install pandas (아나콘다 프롬포트)

# 1. 판다스 패키지
- 데이터 분석을 위해 반드시 알아야할 패키지.
- 넘파이를 기반으로 하며, 다른 많은 라이브러리와 잘 통합되도록 설계됨.
<br>
- 1차원 구조 시리즈, 2차원 구조 데이터프레임 제공.
<br>
- 장점
```
데이터 프레임 생성 용이, 파일 i/o 간편화, 레이블링
부분 데이터 추출, 크기 변경(행/열 삽입 및 삭제 용이)
데이터 분할 및 병합, 데이터 정렬, 결측치 처리, 피벗/언피벗 용이
```

**참조**

판다스 독스 : [Pandas Docs.](https://pandas.pydata.org/docs/)
판다스 API 레퍼런스 : [Pandas API ref.](https://pandas.pydata.org/docs/reference/index.html)

In [6]:
import pandas as pd

pd.__version__

'1.5.3'

In [9]:
#pd.read() : 'encoding=' 기본값 : utf-8
data = pd.read_json('data/ch09_member1.json')
display(data)
print(type(data))

  name  age    email   address job
0  홍길동   20  h@h.com   서울시 관악구   -
1  신길동   40  s@h.com  서울시 영등포구  팀장
2  김길동   30  k@h.com   서울시 동작구   -

<class 'pandas.core.frame.DataFrame'>

In [16]:
# 헤더가 있는 CSV
member3 = pd.read_csv('data/ch09_member3.csv')
member3

  name  age    email   address  job
0  홍길동   20  h@h.com   서울시 관악구  NaN
1  신길동   40  s@h.com  서울시 영등포구   팀장
2  김길동   30  k@h.com   서울시 동작구  NaN

In [17]:
# 헤더가 없는 CSV ; 헤더 설정 가능
member1 = pd.read_csv('data/ch09_member1.csv', 
                    header=None,
                    names=['이름', '나이', '이메일', '주소'] 
                     ) 
member1

    이름  나이               이메일        주소
0  홍길동  20  kildong@hong.com   서울시 관악구
1  김길동  40  kimdong@hong.com  서울시 영등포구
2  신길동  30  sindong@hong.com   서울시 동작구

In [18]:
pd.read_hdf('data/ch09_iris.h5', key='iris')

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

# 2. 데이터 프레임 생성

## 2.1 딕셔너리를 이용한 데이터 프레임 생성

In [22]:
d = {'kor':[100,90], 'mat':[95,97]}
df = pd.DataFrame(data=d)
df

   kor  mat
0  100   95
1   90   97

In [26]:
# 데이터 프레임을 딕셔너리로
df.to_dict()

{'kor': {0: 100, 1: 90}, 'mat': {0: 95, 1: 97}}

In [27]:
# 데이터 프레임을 넘파이 배열으로
df.to_numpy()

array([[100,  95],
       [ 90,  97]], dtype=int64)

In [29]:
# 데이터 프레임은 열별로 동일 자료형을 가짐
d = [{'kor':100, 'mat':95},
    {'kor':90, 'mat':97.5}]
df = pd.DataFrame(d)
df

   kor   mat
0  100  95.0
1   90  97.5

In [32]:
# 데이터 프레임의 열별 타입
print(df.dtypes)
print()
# 데이터 프레임의 정보 확인
df.info()

kor      int64
mat    float64
dtype: object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   kor     2 non-null      int64
 1   mat     2 non-null      float64
dtypes: float64(1), int64(1)
memory usage: 160.0 bytes

In [34]:
# 1차원 데이터 : 시리즈
type(df['kor'])

pandas.core.series.Series

In [35]:
# 데이터 프레임의 열 타입 변경
import numpy as np
df['kor'].astype(np.float64)

0    100.0
1     90.0
Name: kor, dtype: float64

In [36]:
# 열 인덱스에 맞추어 생성 및 결측치 처리
d = [{'kor':100, 'mat':100},{'kor':90, 'mat':95},{'kor':83,'eng':97}]
df = pd.DataFrame(d)
df

   kor    mat   eng
0  100  100.0   NaN
1   90   95.0   NaN
2   83    NaN  97.0

In [37]:
# 결측치의 type : float, 결측치가 있는 열은 float으로 처리됨
type(np.nan)

float

In [39]:
# 결측치는 int로 형변환이 불가함
df['mat'].astype('int32')

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

## 2.2 리스트를 이용한 데이터 프레임 생성

In [41]:
kor = [100,100,95,80,87]
mat = [80,90,65,80,75]
df = pd.DataFrame({'kor':kor, 'mat':mat})
df

   kor  mat
0  100   80
1  100   90
2   95   65
3   80   80
4   87   75

In [44]:
# 두 리스트를 np.c_처리하여 데이터 프레임 생성 및 columns를 통해 헤더 생성
pd.DataFrame(np.c_[kor, mat], columns=['kor', 'mat'])

   kor  mat
0  100   80
1  100   90
2   95   65
3   80   80
4   87   75

In [47]:
l = [[100, 90],[70, 80]]
pd.DataFrame(l, index=['철수', '영희'], columns=['국어','수학'])

     국어  수학
철수  100  90
영희   70  80

- data.go.kr : '상가 상권 정보' 다운로드 - '민간 아파트 분양 가격' 다운로드

In [50]:
%ls "C:/ai/downloads/shareData/상가정보/"

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 0C81-36F7

 C:\ai\downloads\shareData\상가정보 디렉터리

2026-07-08  오후 12:07    <DIR>          .
2026-07-14  오후 05:46    <DIR>          ..
2025-11-03  오전 12:45             1,011 [필독]파일열람방법.txt
2026-04-27  오전 11:10        61,321,696 소상공인시장진흥공단_상가(상권)정보_강원_202603.csv
2026-04-27  오전 11:10       367,852,181 소상공인시장진흥공단_상가(상권)정보_경기_202603.csv
2026-04-27  오전 11:10        92,474,293 소상공인시장진흥공단_상가(상권)정보_경남_202603.csv
2026-04-27  오전 11:10        76,309,810 소상공인시장진흥공단_상가(상권)정보_경북_202603.csv
2026-04-27  오전 11:10        40,031,721 소상공인시장진흥공단_상가(상권)정보_광주_202603.csv
2026-04-27  오전 11:10        61,825,564 소상공인시장진흥공단_상가(상권)정보_대구_202603.csv
2026-04-27  오전 11:10        41,866,930 소상공인시장진흥공단_상가(상권)정보_대전_202603.csv
2026-04-27  오전 11:10        84,329,596 소상공인시장진흥공단_상가(상권)정보_부산_202603.csv
2026-04-27  오전 11:10       292,646,735 소상공인시장진흥공단_상가(상권)정보_서울_202603.csv
2026-04-27  오전 11:10         9,651,297 소상공인시장진흥공단_상가(상권)정보_세종_202603.csv
2026-04-27  오전 11:10        28,285,232 소상공인시장진흥공단_상가(상권)정보_울산_202603.csv
2026-04-27  오전 11:10        74,007,608 소상공인시장진흥공단_상가(상권)정보_인천_202603.csv
2026-04-27  오전 11:10        53,165,985 소상공인시장진흥공단_상가(상권)정보_전남_202603.csv
2026-04-27  오전 11:10        56,632,709 소상공인시장진흥공단_상가(상권)정보_전북_202603.csv
2026-04-27  오전 11:10        32,746,698 소상공인시장진흥공단_상가(상권)정보_제주_202603.csv
2026-04-27  오전 11:10        66,764,669 소상공인시장진흥공단_상가(상권)정보_충남_202603.csv
2026-04-27  오전 11:10        50,941,247 소상공인시장진흥공단_상가(상권)정보_충북_202603.csv
              18개 파일       1,490,854,982 바이트
               2개 디렉터리  145,154,404,352 바이트 남음

In [56]:
df = pd.read_csv(r'C:/ai/downloads/shareData/상가정보/소상공인시장진흥공단_상가(상권)정보_세종_202603.csv',
                #encoding='utf-8', sep=',' : 기본값
                nrows = 30, # 첫 30행 불러오기
                low_memory=False, # 데이터 용량이 클 경우 사용
                )
df.shape # 데이터 프레임 크기

(30, 39)

In [55]:
df.head(1) # 상위 1행

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,MA010120220813963449,레인카페,NaN,I2,음식,I212,비알코올,I21201,카페,I56229,...,4473025021101010001038753,NaN,세종특별자치시 세종특별자치시 조치원읍 조치원8길 16,339883.0,30027,NaN,지,NaN,127.300453,36.600906

In [60]:
# 데이터 프레임 디스플레이 옵션
pd.options.display.max_columns = 40 # 40열까지 display
pd.options.display.max_rows = 40 # 40행까지 display

In [63]:
df.head(3).T # 상위 3행을 전치

,0,1,2
상가업소번호,MA010120220813963449,MA010120220805872513,MA010120220700019175
상호명,레인카페,수와마을,세종수이비인후과의원
지점명,NaN,NaN,NaN
상권업종대분류코드,I2,I2,Q1
상권업종대분류명,음식,음식,보건의료
상권업종중분류코드,I212,I201,Q102
상권업종중분류명,비알코올,한식,의원
상권업종소분류코드,I21201,I20101,Q10201
상권업종소분류명,카페,백반/한정식,내과/소아과 의원
표준산업분류코드,I56229,I56111,Q86201
표준산업분류명,기타 비알코올 음료점업,한식 일반 음식점업,일반의원
시도코드,36,36,36
시도명,세종특별자치시,세종특별자치시,세종특별자치시
시군구코드,36110,36110,36110
시군구명,세종특별자치시,세종특별자치시,세종특별자치시
행정동코드,36110250,36110250,36110525
행정동명,조치원읍,조치원읍,해밀동
법정동코드,3611025021,3611025030,3611011600
법정동명,조치원읍,조치원읍,해밀동
지번코드,3611025021101010001,3611025030103790016,3611011600200050002
대지구분코드,1,1,2
대지구분명,대지,대지,산
지번본번지,101,379,5
지번부번지,1.0,16.0,2.0
지번주소,세종특별자치시 세종특별자치시 조치원읍 원리 101-1,세종특별자치시 세종특별자치시 조치원읍 죽림리 379-16,세종특별자치시 세종특별자치시 해밀동 산 5-2
도로명코드,361104574473,361103258034,361103352828
도로명,세종특별자치시 세종특별자치시 조치원읍 조치원8길,세종특별자치시 세종특별자치시 조치원읍 충현로,세종특별자치시 세종특별자치시 해밀3로
건물본번지,16,75,43
건물부번지,NaN,1.0,NaN
건물관리번호,4473025021101010001038753,4473025030103790016042253,3611011600200050002000001
건물명,NaN,NaN,행정중심복합도시
도로명주소,세종특별자치시 세종특별자치시 조치원읍 조치원8길 16,세종특별자치시 세종특별자치시 조치원읍 충현로 75-1,세종특별자치시 세종특별자치시 해밀3로 43
구우편번호,339883.0,339884.0,NaN
신우편번호,30027,30034,30092
동정보,NaN,NaN,NaN
층정보,지,NaN,NaN
호정보,NaN,NaN,NaN
경도,127.300453,127.296263,127.264487
위도,36.600906,36.595303,36.528585

## 2.3 read_csv

- csv 파일 불러오기

In [21]:
# csv 파일 불러오기(기본값) : '#'을 생략하지 않음
import pandas as pd
member = pd.read_csv('data/ch11_member.csv')
member

   Name   Age          Email  Address       Birth
0   홍길동  20.0  hong@hong.com  서울시 강동구  1999-01-01
1   홍길서  30.0   seo@hong.com   서울시 중구  1999-12-01
2   홍길남  21.0   nam@hong.com  서울시 강동구  1999-11-01
3   홍길북  22.0   buk@hong.com  서울시 관악구  1999-05-01
4   홍길중  23.0   mid@hong.com   부산시 중구  1999-01-30
5  #홍길뜽   NaN    non@not.com      없는구  2000-01-01

In [22]:
member.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     6 non-null      object
 1   Age      5 non-null      float64
 2   Email    6 non-null      object
 3   Address  6 non-null      object
 4   Birth    6 non-null      object
dtypes: float64(1), object(4)
memory usage: 368.0+ bytes

In [23]:
# 문자형으로 변환
member['Age'] = member['Age'].astype('str') # Out 출력이 있을 경우, 할당 필요

In [24]:
member['Age'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 6 entries, 0 to 5
Series name: Age
Non-Null Count  Dtype
--------------  -----
6 non-null      object
dtypes: object(1)
memory usage: 176.0+ bytes

In [25]:
member.loc[0, 'Age']

'20.0'

In [41]:
# 숫자형으로 변환
member['Age'] = pd.to_numeric(member['Age'], 
                              errors='coerce'
                             # 숫자로 바꿀 수 없는 값을 결측치(NaN)로 강제 변환
                             )
member['Age'] = member['Age'].astype('Int64')

member
# member['Age'].astype('int16')

# import numpy as np
# member['Age'].astype(np.float64)

   Name   Age          Email  Address      Birth  year  month  day
0   홍길동    20  hong@hong.com  서울시 강동구 1999-01-01  1999      1    1
1   홍길서    30   seo@hong.com   서울시 중구 1999-12-01  1999     12    1
2   홍길남    21   nam@hong.com  서울시 강동구 1999-11-01  1999     11    1
3   홍길북    22   buk@hong.com  서울시 관악구 1999-05-01  1999      5    1
4   홍길중    23   mid@hong.com   부산시 중구 1999-01-30  1999      1   30
5  #홍길뜽  <NA>    non@not.com      없는구 2000-01-01  2000      1    1

In [42]:
 pd.to_numeric(member['Age'], 
               downcast='integer',
               # Age의 문자열을 integer 중 적용 가능한 가장 작은 타입으로 형변환
               errors='ignore'
               # 숫자로 바꿀 수 없는 데이터(ex:3,000)는 원본 데이터를 그대로 반환 (object or 기존 타입)
              )
member.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     6 non-null      object
 1   Age      5 non-null      Int64
 2   Email    6 non-null      object
 3   Address  6 non-null      object
 4   Birth    6 non-null      datetime64[ns]
 5   year     6 non-null      int64
 6   month    6 non-null      int64
 7   day      6 non-null      int64
dtypes: Int64(1), datetime64[ns](1), int64(3), object(3)
memory usage: 518.0+ bytes

In [37]:
# object로 읽어들인 Birth를 datetime형으로
member['Birth'] = member['Birth'].astype('datetime64[ns]') # 데이터 형태 : YYYY-MM-DD
member.astype({'Birth':'datetime64[ns]', 'Age':'Int32'})
pd.to_datetime(member['Birth'],
              #format='%Y-%m-%d %H:%M:%S'
              )
member.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     6 non-null      object
 1   Age      5 non-null      Int64
 2   Email    6 non-null      object
 3   Address  6 non-null      object
 4   Birth    6 non-null      datetime64[ns]
 5   year     6 non-null      int64
 6   month    6 non-null      int64
 7   day      6 non-null      int64
dtypes: Int64(1), datetime64[ns](1), int64(3), object(3)
memory usage: 518.0+ bytes

In [38]:
# 날짜형 데이터의 년-월-일 분할
member['year'] = member.Birth.dt.year
member['month'] = member.Birth.dt.month
member['day'] = member.Birth.dt.day

In [39]:
member

   Name   Age          Email  Address      Birth  year  month  day
0   홍길동    20  hong@hong.com  서울시 강동구 1999-01-01  1999      1    1
1   홍길서    30   seo@hong.com   서울시 중구 1999-12-01  1999     12    1
2   홍길남    21   nam@hong.com  서울시 강동구 1999-11-01  1999     11    1
3   홍길북    22   buk@hong.com  서울시 관악구 1999-05-01  1999      5    1
4   홍길중    23   mid@hong.com   부산시 중구 1999-01-30  1999      1   30
5  #홍길뜽  <NA>    non@not.com      없는구 2000-01-01  2000      1    1

In [439]:
current_date = pd.to_datetime('2026-07-15')
member['일수'] = (current_date - member.Birth).dt.days
member

  Name  Age          Email  Address      Birth     일수
0  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01  10057
1  홍길서   30   seo@hong.com   서울시 중구 1999-12-01   9723
2  홍길남   21            NaN  서울시 강동구 1999-11-01   9753
3  홍길북   22   buk@hong.com  서울시 관악구 1999-05-01   9937
4  홍길중   23            NaN   부산시 중구 1999-01-30  10028

In [50]:
# 특정 행을 제외하고 cp949 파일 불러오기
member = pd.read_csv('data/ch11_membercp949.csv', 
                     encoding = 'cp949',
                    skiprows=[1,6] #1, 6 행 제외하고 불러오기
                    )
member

  Name  Age         Email  Address       Birth
0  홍길서   30  seo@hong.com   서울시 중구  1999-12-01
1  홍길남   21  nam@hong.com  서울시 강동구  1999-11-01
2  홍길북   22  buk@hong.com  서울시 관악구  1999-05-01
3  홍길중   23  mid@hong.com   부산시 중구  1999-01-30

In [53]:
# sep='|', 주석(#) 제외, 상위 n행, datetime형 필드 지정
member_df = pd.read_csv('data/ch11_membersep.csv',
                       sep='|', # '|' 기준으로 데이터를 분리해 읽기
                       comment='#', # 주석(#) 제외
                       nrows=3, # 상위 3행만 불러오기
                       parse_dates=['Birth']) # datetime형 필드 지정

member_df

  Name  Age          Email  Address      Birth
0  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
1  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
2  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01

In [55]:
member_df = pd.read_csv('data/ch11_membertab.csv',
                       sep='\t',
                       comment='#',
                       parse_dates=['Birth'])

member_df

  Name  Age          Email  Address      Birth
0  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
1  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
2  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01
3  홍길북   22   buk@hong.com  서울시 관악구 1999-05-01
4  홍길중   23   mid@hong.com   부산시 중구 1999-01-30

## 2.4 패키지에서 가져오기
- 예시 : iris data 가져오기
    * 방법 1) sklearn (머신러닝 패키지)
    * 방법 2) statsmodels (R 데이터 패키지)
    * 방법 3) seaborn (시각화 패키지)
    
### 2.4.1 sklearn
- 머신러닝을 공부하기 위한 학습용 데이터셋 제공
    * sklearn pkg dataset : 독립변수(입력변수)와 종속변수(타겟변수)가 분리된 딕셔너리 형태로 제공
 - sklearn.datsets 모듈의 데이터를 데이터 프레임으로 변환

In [57]:
# sklearn을 통해 iris data 가져오기
from sklearn import datasets
iris = datasets.load_iris() # 딕셔너리 형태
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [58]:
#iris 데이터셋에 대한 설명
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica

    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
    :Class Distribution: 33.3% for each of 3 classes.
    :Creator: R.A. Fisher
    :Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
    :Date: July, 1988

The famous Iris database, first used by Sir R.A. Fisher. The dataset is taken
from Fisher's paper. Note that it's the same as in R, but not as in the UCI
Machine Learning Repository, which has two wrong data points.

This is perhaps the best known database to be found in the
pattern recognition literature.  Fisher's paper is a classic in the field and
is referenced frequently to this day.  (See Duda & Hart, for example.)  The
data set contains 3 classes of 50 instances each, where each class refers to a
type of iris plant.  One class is linearly separable from the other 2; the
latter are NOT linearly separable from each other.

.. topic:: References

   - Fisher, R.A. "The use of multiple measurements in taxonomic problems"
     Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to
     Mathematical Statistics" (John Wiley, NY, 1950).
   - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.
     (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.
   - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System
     Structure and Classification Rule for Recognition in Partially Exposed
     Environments".  IEEE Transactions on Pattern Analysis and Machine
     Intelligence, Vol. PAMI-2, No. 1, 67-71.
   - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions
     on Information Theory, May 1972, 431-433.
   - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II
     conceptual clustering system finds 3 classes in the data.
   - Many, many more ...

In [60]:
iris.data # 독립변수
iris['data'][:3]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

In [61]:
iris.feature_names # 독립변수의 열 이름(인덱스)

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [63]:
# 데이터프레임에서의 독립변수 열 이름 (' ' 또는 특수문자 '()' 사용 불가)
[col[:-5].replace(' ', '_') for col in iris.feature_names]

['sepal_length', 'sepal_width', 'petal_length', 'petal_width']

In [64]:
# 종속변수(타겟변수)
iris.target
iris['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [66]:
iris.target_names
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [68]:
# 데이터 프레임의 가장 오른쪽 열(타겟변수;species)
iris.target_names[iris.target]
iris['target_names'][iris['target']]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica'], dtype='<U10')

In [73]:
# 독립변수 [col[:-5].replace(' ', '_') for col in iris.feature_names]
data = iris.data
print(data[::50])
# 종속변수 species
target = iris.target_names[iris.target].reshape(-1, 1)
print(target[::50])

[[5.1 3.5 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.3 3.3 6.  2.5]]
[['setosa']
 ['versicolor']
 ['virginica']]

In [75]:
print('독립변수의 차원 수 :', data.shape)
print('종속변수의 차원 수 :', target.shape)

독립변수의 차원 수 : (150, 4)
종속변수의 차원 수 : (150, 1)

In [92]:
# 독립변수와 종속변수를 stack한 후, 데이터 프레임으로 생성
result = np.c_[data, target]
df = pd.DataFrame(result, columns=[col[:-5].replace(' ', '_') for col in iris.feature_names]+['species'])
df.head() # 기본값 : 상위 5행
df.tail() # 기본값 : 하위 5행

    sepal_length sepal_width petal_length petal_width    species
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

In [84]:
df['petal_width'][:3]
df.petal_width[:3]

0    0.2
1    0.2
2    0.2
Name: petal_width, dtype: object

In [85]:
df = pd.DataFrame(result, columns=iris.feature_names+['species'])
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [87]:
# 열 이름에 띄워쓰기 또는 특수문자가 있을 경우
df['petal width (cm)'][:3]
# df.petal width (cm)[:3]

0    0.2
1    0.2
2    0.2
Name: petal width (cm), dtype: object

In [90]:
# 독립변수와 종속변수를 각각 데이터 프레임으로 생성 후 두 데이터 프레임을 연결
# X : 독립변수 데이터 프레임 ; 변수 개수가 많을 경우 대문자 사용
X = pd.DataFrame(data, columns=[col[:-5].replace(' ','_') for col in iris.feature_names])
X.head(1)

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2

In [91]:
# y : 종속변수 데이터 프레임 ; 변수 개수가 하나일 경우 소문자 사용
y = pd.DataFrame(target, columns=['species'])
y.tail()

       species
145  virginica
146  virginica
147  virginica
148  virginica
149  virginica

In [93]:
print(X.index) # index : 행이름

RangeIndex(start=0, stop=150, step=1)

In [98]:
# 두 데이터 프레임을 연결 
iris_df = pd.concat([X, y],
                    axis = 1 # 기본값 : 0
                   )
iris_df[::25]

     sepal_length  sepal_width  petal_length  petal_width     species
0             5.1          3.5           1.4          0.2      setosa
25            5.0          3.0           1.6          0.2      setosa
50            7.0          3.2           4.7          1.4  versicolor
75            6.6          3.0           4.4          1.4  versicolor
100           6.3          3.3           6.0          2.5   virginica
125           7.2          3.2           6.0          1.8   virginica

### 2.4.2 statsmodels

In [100]:
from statsmodels.api import datasets
iris_dataset = datasets.get_rdataset('iris',
                                    package='datasets',
                                    cache=True # 기본값 False ; 캐시 생성 없이 데이터를 불러옴 
                                    )          # True로 변경 ; 캐시 데이터를 PC에 저장
iris = iris_dataset.data
iris.head()

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [101]:
# 열 이름에 '.'이 있는 경우 "데이터프레임['열']" 형식만 사용 가능
iris['Sepal.Length'][:5]

0    5.1
1    4.9
2    4.7
3    4.6
4    5.0
Name: Sepal.Length, dtype: float64

In [105]:
# 열 이름 수정
iris.columns = [col.replace('.','_').lower() for col in iris.columns]
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

### 2.4.3 seaborn

In [106]:
import seaborn as sns
iris = sns.load_dataset('iris')
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [107]:
# 데이터 프레임을 파일로 출력
iris.to_csv('data/ch11_iris.csv') # 기본값 : sep=',', encoding='utf-8', index=True

In [109]:
# 행 이름이 추가되어 있음
pd.read_csv('data/ch11_iris.csv')[:5]

   Unnamed: 0  sepal_length  sepal_width  petal_length  petal_width species
0           0           5.1          3.5           1.4          0.2  setosa
1           1           4.9          3.0           1.4          0.2  setosa
2           2           4.7          3.2           1.3          0.2  setosa
3           3           4.6          3.1           1.5          0.2  setosa
4           4           5.0          3.6           1.4          0.2  setosa

In [111]:
# 행 이름을 생략하여 파일로 출력
iris.to_csv('data/ch11_iris.csv', index=False)

In [112]:
# 파일을 압축하여 출력
iris.to_csv('data/ch11_iris.zip',
           index=False,
           compression='infer' # 파일 확장자(.zip, .gz, .bz2)를 확인 후 압축 형식을 따름
           )

In [114]:
load_iris = pd.read_csv('data/ch11_iris.csv')
load_iris.sample(3) # 임의의 3행 반환

    sepal_length  sepal_width  petal_length  petal_width     species
49           5.0          3.3           1.4          0.2      setosa
46           5.1          3.8           1.6          0.2      setosa
76           6.8          2.8           4.8          1.4  versicolor

In [115]:
load_iris = pd.read_csv('data/ch11_iris.zip', compression='infer')
load_iris.sample(3)

     sepal_length  sepal_width  petal_length  petal_width     species
107           7.3          2.9           6.3          1.8   virginica
81            5.5          2.4           3.7          1.0  versicolor
98            5.1          2.5           3.0          1.1  versicolor

# 3. 이름 지정하기

## 3.1 열 이름 지정하기

In [150]:
member = pd.read_csv('data/ch11_member.csv', comment='#', parse_dates=['Birth'])
member

  Name  Age          Email  Address      Birth
0  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
1  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
2  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01
3  홍길북   22   buk@hong.com  서울시 관악구 1999-05-01
4  홍길중   23   mid@hong.com   부산시 중구 1999-01-30

In [151]:
# 열 이름 확인하기
member.columns

Index(['Name', 'Age', 'Email', 'Address', 'Birth'], dtype='object')

Index(['Name', 'Age', 'Email', 'Address', 'Birth'], dtype='object')
; column name's level  : 1

In [152]:
# 열 이름 지정하기
member.columns = ['성명', '나이', '이메일', '주소', '생일']
member

    성명  나이            이메일       주소         생일
0  홍길동  20  hong@hong.com  서울시 강동구 1999-01-01
1  홍길서  30   seo@hong.com   서울시 중구 1999-12-01
2  홍길남  21   nam@hong.com  서울시 강동구 1999-11-01
3  홍길북  22   buk@hong.com  서울시 관악구 1999-05-01
4  홍길중  23   mid@hong.com   부산시 중구 1999-01-30

## 3.2 행 이름 지정하기

In [153]:
# 행 이름 확인하기
member.index

RangeIndex(start=0, stop=5, step=1)

In [154]:
# 행 이름 지정하기 1
member.index = range(1, 6)
member

    성명  나이            이메일       주소         생일
1  홍길동  20  hong@hong.com  서울시 강동구 1999-01-01
2  홍길서  30   seo@hong.com   서울시 중구 1999-12-01
3  홍길남  21   nam@hong.com  서울시 강동구 1999-11-01
4  홍길북  22   buk@hong.com  서울시 관악구 1999-05-01
5  홍길중  23   mid@hong.com   부산시 중구 1999-01-30

In [155]:
# 행 이름 지정하기 2
member.index = ['동', '서', '남', '북', '중']
member

    성명  나이            이메일       주소         생일
동  홍길동  20  hong@hong.com  서울시 강동구 1999-01-01
서  홍길서  30   seo@hong.com   서울시 중구 1999-12-01
남  홍길남  21   nam@hong.com  서울시 강동구 1999-11-01
북  홍길북  22   buk@hong.com  서울시 관악구 1999-05-01
중  홍길중  23   mid@hong.com   부산시 중구 1999-01-30

In [156]:
print(member.index)
print(member.index.name)

Index(['동', '서', '남', '북', '중'], dtype='object')
None

In [157]:
# ex) 이름을 행 이름(index)으로 지정하기
#     (1) 할당 (2) inplace 매개변수에 True (기본값 : False)
member.set_index('성명', inplace=True)
member

     나이            이메일       주소         생일
성명
홍길동  20  hong@hong.com  서울시 강동구 1999-01-01
홍길서  30   seo@hong.com   서울시 중구 1999-12-01
홍길남  21   nam@hong.com  서울시 강동구 1999-11-01
홍길북  22   buk@hong.com  서울시 관악구 1999-05-01
홍길중  23   mid@hong.com   부산시 중구 1999-01-30

In [158]:
print(member.index)
print(member.columns) # 열 이름에서 '이름'열이 없어짐

Index(['홍길동', '홍길서', '홍길남', '홍길북', '홍길중'], dtype='object', name='성명')
Index(['나이', '이메일', '주소', '생일'], dtype='object')

In [160]:
# 행 이름(index)을 열에 편입하기
member.reset_index(inplace=True)

In [166]:
member.index=[0,4,1,2,3] # 나이순 sort()로 가정

In [168]:
# 기존 행 이름을 0부터 numbering (지양)
member.index = range(len(member))
member

    성명  나이            이메일       주소         생일
0  홍길동  20  hong@hong.com  서울시 강동구 1999-01-01
1  홍길서  30   seo@hong.com   서울시 중구 1999-12-01
2  홍길남  21   nam@hong.com  서울시 강동구 1999-11-01
3  홍길북  22   buk@hong.com  서울시 관악구 1999-05-01
4  홍길중  23   mid@hong.com   부산시 중구 1999-01-30

In [171]:
# 기존 행 이름을 0부터 numbering (지향)
member.reset_index(drop=True, # 기존 행 이름을 열에 편입하지 않고 제거 후 숫자 index를 초기화
                   inplace=True)
member

    성명  나이            이메일       주소         생일
0  홍길동  20  hong@hong.com  서울시 강동구 1999-01-01
1  홍길서  30   seo@hong.com   서울시 중구 1999-12-01
2  홍길남  21   nam@hong.com  서울시 강동구 1999-11-01
3  홍길북  22   buk@hong.com  서울시 관악구 1999-05-01
4  홍길중  23   mid@hong.com   부산시 중구 1999-01-30

## 3.3 레벨 이름 지정하기

In [172]:
print(member.columns)
print(member.columns.name)
display(member)

Index(['성명', '나이', '이메일', '주소', '생일'], dtype='object')
None

    성명  나이            이메일       주소         생일
0  홍길동  20  hong@hong.com  서울시 강동구 1999-01-01
1  홍길서  30   seo@hong.com   서울시 중구 1999-12-01
2  홍길남  21   nam@hong.com  서울시 강동구 1999-11-01
3  홍길북  22   buk@hong.com  서울시 관악구 1999-05-01
4  홍길중  23   mid@hong.com   부산시 중구 1999-01-30

In [173]:
member.columns.name = '열 이름'
member

열 이름   성명  나이            이메일       주소         생일
0     홍길동  20  hong@hong.com  서울시 강동구 1999-01-01
1     홍길서  30   seo@hong.com   서울시 중구 1999-12-01
2     홍길남  21   nam@hong.com  서울시 강동구 1999-11-01
3     홍길북  22   buk@hong.com  서울시 관악구 1999-05-01
4     홍길중  23   mid@hong.com   부산시 중구 1999-01-30

In [174]:
# 열 레벨이 2개 이상인 데이터 프레임 생성
member.columns = [['필수정보','필수정보','필수정보','선택정보','선택정보'],
                 ['성명', '나이', '이메일', '주소', '생년월일']]

In [183]:
member.columns.names = ['대분류','소분류']
member

대분류  필수정보                        선택정보
소분류    성명  나이            이메일       주소       생년월일
좌우 동  홍길동  20  hong@hong.com  서울시 강동구 1999-01-01
   서  홍길서  30   seo@hong.com   서울시 중구 1999-12-01
상하 남  홍길남  21   nam@hong.com  서울시 강동구 1999-11-01
   북  홍길북  22   buk@hong.com  서울시 관악구 1999-05-01
중앙 중  홍길중  23   mid@hong.com   부산시 중구 1999-01-30

In [188]:
# 행 레벨이 2개 이상인 데이터 프레임 생성
member.index = [['좌우','좌우','상하','상하','중앙'],
                 ['동', '서', '남', '북', '중']]
member.index.names = ['레벨 1','레벨 2']
member

대분류       필수정보                        선택정보
소분류         성명  나이            이메일       주소       생년월일
레벨 1 레벨 2
좌우   동     홍길동  20  hong@hong.com  서울시 강동구 1999-01-01
     서     홍길서  30   seo@hong.com   서울시 중구 1999-12-01
상하   남     홍길남  21   nam@hong.com  서울시 강동구 1999-11-01
     북     홍길북  22   buk@hong.com  서울시 관악구 1999-05-01
중앙   중     홍길중  23   mid@hong.com   부산시 중구 1999-01-30

In [189]:
member[('필수정보', '성명')]

레벨 1  레벨 2
좌우    동       홍길동
      서       홍길서
상하    남       홍길남
      북       홍길북
중앙    중       홍길중
Name: (필수정보, 성명), dtype: object

In [192]:
member.loc[('상하', '남'),('필수정보', '성명')]

'홍길남'

In [193]:
member.xs(key='남', level='레벨 2')

대분류  필수정보                       선택정보
소분류    성명  나이           이메일       주소       생년월일
레벨 1
상하    홍길남  21  nam@hong.com  서울시 강동구 1999-11-01

In [195]:
member.loc['좌우','필수정보']

소분류    성명  나이            이메일
레벨 2
동     홍길동  20  hong@hong.com
서     홍길서  30   seo@hong.com

# 4. 부분 데이터 조회

In [349]:
member = pd.read_csv('data/ch11_member.csv', comment='#', parse_dates=['Birth'])
member

  Name  Age          Email  Address      Birth
0  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
1  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
2  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01
3  홍길북   22   buk@hong.com  서울시 관악구 1999-05-01
4  홍길중   23   mid@hong.com   부산시 중구 1999-01-30

## 4.1 열 조회
- df[열 이름]
- df[조건]

In [350]:
# 열 이름으로 호출하기
member['Name']

0    홍길동
1    홍길서
2    홍길남
3    홍길북
4    홍길중
Name: Name, dtype: object

In [351]:
# 둘 이상의 열 이름으로 호출하기
member[['Name','Age','Birth']]

  Name  Age      Birth
0  홍길동   20 1999-01-01
1  홍길서   30 1999-12-01
2  홍길남   21 1999-11-01
3  홍길북   22 1999-05-01
4  홍길중   23 1999-01-30

## 4.2 loc 조회
- df.loc[행 이름, 열 이름] : 행 이름과 열 이름으로 조회
    * 슬라이싱 가능 [from:to] : from부터 to까지
    * list를 이용한 조회 가능 : 연속되지 않거나 원하는 특정 행/열
    * 열 이름 생략 시 모든 열 조회 
    
    
### 슬라이싱

In [352]:
# 행 이름(index)으로 호출하기
member.loc[0]

Name                       홍길동
Age                         20
Email            hong@hong.com
Address                서울시 강동구
Birth      1999-01-01 00:00:00
Name: 0, dtype: object

In [353]:
# 인덱스 슬라이싱
member.loc[0:2]
member.loc[0:2, :]
member.loc[0:2, ...]

  Name  Age          Email  Address      Birth
0  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
1  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
2  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01

In [354]:
# 행 이름 슬라이싱
member.index = ['동', '서', '남', '북', '중']
member.loc['동':'남']

  Name  Age          Email  Address      Birth
동  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
서  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
남  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01

In [355]:
# 슬라이싱을 이용한 특정 정보 추출
member.loc['동':'남','Name':'Email']

  Name  Age          Email
동  홍길동   20  hong@hong.com
서  홍길서   30   seo@hong.com
남  홍길남   21   nam@hong.com

### list

In [356]:
# 동행과 남행만 조회
member.loc[['동', '남']]

  Name  Age          Email  Address      Birth
동  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
남  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01

In [357]:
# 동행과 남행의 Name과 Email만 조회
member.loc[['동','남'],['Name', 'Email']]

  Name          Email
동  홍길동  hong@hong.com
남  홍길남   nam@hong.com

In [358]:
# 모든 행의 Name
member.loc[:,'Name'] # 하나의 열 또는 행을 조회할 경우, 결과는 1차원 시리즈로 나타남
member.loc[...,'Name'] # 행의 경우, : 또는 ... 등을 비워둘 수 없음

동    홍길동
서    홍길서
남    홍길남
북    홍길북
중    홍길중
Name: Name, dtype: object

In [359]:
# 2차원 데이터는 데이터 프레임
member.loc[['동']]

  Name  Age          Email  Address      Birth
동  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01

In [360]:
# 1차원 데이터는 시리즈
member.loc['동']

Name                       홍길동
Age                         20
Email            hong@hong.com
Address                서울시 강동구
Birth      1999-01-01 00:00:00
Name: 동, dtype: object

In [361]:
type(member.loc[['동']]), type(member.loc['동'])

(pandas.core.frame.DataFrame, pandas.core.series.Series)

## 4.3 iloc 조회
- df.iloc[행 번호, 열 번호]
    * 슬라이싱 가능 [from:stop:by] : from부터 stop 전까지 by씩 건너뜀
    * list 조회 가능
    * 열 번호 생략 시 모든 열 조회
    
    
### 슬라이싱

In [362]:
member

  Name  Age          Email  Address      Birth
동  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
서  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
남  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01
북  홍길북   22   buk@hong.com  서울시 관악구 1999-05-01
중  홍길중   23   mid@hong.com   부산시 중구 1999-01-30

In [363]:
# 서부터 남까지 조회
member.iloc[1:3]

  Name  Age         Email  Address      Birth
서  홍길서   30  seo@hong.com   서울시 중구 1999-12-01
남  홍길남   21  nam@hong.com  서울시 강동구 1999-11-01

In [364]:
# 1차원 데이터는 시리즈
member.iloc[0]

Name                       홍길동
Age                         20
Email            hong@hong.com
Address                서울시 강동구
Birth      1999-01-01 00:00:00
Name: 동, dtype: object

In [365]:
# 2차원 데이터는 데이터 프레임
member.iloc[[0]]

  Name  Age          Email  Address      Birth
동  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01

In [366]:
# 0~2 행, 1~2 열
member.iloc[0:3,1:3]

   Age          Email
동   20  hong@hong.com
서   30   seo@hong.com
남   21   nam@hong.com

In [367]:
# 짝수번째 행 / 마지막 열 제외
member.iloc[::2,:-1:]

  Name  Age          Email  Address
동  홍길동   20  hong@hong.com  서울시 강동구
남  홍길남   21   nam@hong.com  서울시 강동구
중  홍길중   23   mid@hong.com   부산시 중구

In [368]:
# 마지막 행부터 첫 행까지 뒤집어 출력
member.iloc[::-1]

  Name  Age          Email  Address      Birth
중  홍길중   23   mid@hong.com   부산시 중구 1999-01-30
북  홍길북   22   buk@hong.com  서울시 관악구 1999-05-01
남  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01
서  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
동  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01

### list

In [369]:
# 0, 2 행 / 1, 3열
member.iloc[[0,2],[1,3]]

   Age  Address
동   20  서울시 강동구
남   21  서울시 강동구

In [370]:
# 1, 4 행 / 2, 4열
member.iloc[[1,4],[2,4]]

          Email      Birth
서  seo@hong.com 1999-12-01
중  mid@hong.com 1999-01-30

In [371]:
member.iloc[[2,4]]

  Name  Age         Email  Address      Birth
남  홍길남   21  nam@hong.com  서울시 강동구 1999-11-01
중  홍길중   23  mid@hong.com   부산시 중구 1999-01-30

## 4.4 조건 조회

In [372]:
member

  Name  Age          Email  Address      Birth
동  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
서  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
남  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01
북  홍길북   22   buk@hong.com  서울시 관악구 1999-05-01
중  홍길중   23   mid@hong.com   부산시 중구 1999-01-30

In [373]:
member['Age']>=23

동    False
서     True
남    False
북    False
중     True
Name: Age, dtype: bool

In [374]:
member.loc[[False, True, False, False, True]]

  Name  Age         Email Address      Birth
서  홍길서   30  seo@hong.com  서울시 중구 1999-12-01
중  홍길중   23  mid@hong.com  부산시 중구 1999-01-30

In [375]:
# 23세 이상 데이터
member.loc[member['Age']>=23]
member.loc[member['Age']>=23, :]
member[member['Age']>=23]

  Name  Age         Email Address      Birth
서  홍길서   30  seo@hong.com  서울시 중구 1999-12-01
중  홍길중   23  mid@hong.com  부산시 중구 1999-01-30

In [376]:
# 23세 이상의 Name, Age, Email 데이터 조회 ; 슬라이싱 이용
member.loc[member['Age']>=23, 'Name':'Email']

  Name  Age         Email
서  홍길서   30  seo@hong.com
중  홍길중   23  mid@hong.com

In [377]:
# 23세 미만의 데이터
member[~(member['Age']>=23)] # ~[조건] : 조건의 반대값

  Name  Age          Email  Address      Birth
동  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
남  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01
북  홍길북   22   buk@hong.com  서울시 관악구 1999-05-01

In [378]:
# 특정 단어가 포함되어 있는지 확인하기
address = '서울시 관악구 신림동'
address.find('신림동')!=-1
address.startswith('서울시')

True

In [379]:
member['Address'].find('중구') # 시리즈에 문자 함수를 바로 사용할 수 없음

AttributeError: 'Series' object has no attribute 'find'

※ 시리즈에 문자 함수를 사용하기 위한 참조 :
[String handling](https://pandas.pydata.org/pandas-docs/stable/reference/series.html#string-handling)

<br>

* Series.str.find()

In [380]:
# Address에 중구가 포함된 데이터
member[member['Address'].str.find('중구')!=-1] # [조건]!=[결과] : [조건]의 [결과]가 일치하지 않을 때 True
member.loc[member['Address'].str.find('중구')!=-1]

  Name  Age         Email Address      Birth
서  홍길서   30  seo@hong.com  서울시 중구 1999-12-01
중  홍길중   23  mid@hong.com  부산시 중구 1999-01-30

In [381]:
# Address에 중구가 포함된, Name, Email 데이터
member.loc[member['Address'].str.find('중구')!=-1, ['Name', 'Email']]

  Name         Email
서  홍길서  seo@hong.com
중  홍길중  mid@hong.com

* Series.str.contains(value1|value2): 시리즈 내에 value1 또는 value2가 있을 경우, value를 반환

In [382]:
# Address에 관악구 또는 중구가 포함된 데이터
member[member['Address'].str.contains('중구|관악구')]

  Name  Age         Email  Address      Birth
서  홍길서   30  seo@hong.com   서울시 중구 1999-12-01
북  홍길북   22  buk@hong.com  서울시 관악구 1999-05-01
중  홍길중   23  mid@hong.com   부산시 중구 1999-01-30

In [383]:
# Address에 서울이 포함되지 않은 데이터
member[~member['Address'].str.startswith('서울')]

  Name  Age         Email Address      Birth
중  홍길중   23  mid@hong.com  부산시 중구 1999-01-30

In [384]:
# Name이 홍길동이거나 홍길남인 데이터의 모든 열 1
member[(member['Name']=='홍길동')|(member['Name']=='홍길남')]

  Name  Age          Email  Address      Birth
동  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
남  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01

- Series.isin(values) : 시리즈 내에 values가 있을 경우, values를 반환

In [385]:
# Name이 홍길동이거나 홍길남인 데이터의 모든 열 2
member[member['Name'].isin(['홍길동', '홍길남', '홍길서'])]

  Name  Age          Email  Address      Birth
동  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
서  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
남  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01

In [386]:
# Name이 홍길동이거나 홍길남이거나 홍길서인 데이터의 Name, Age, Email
member.loc[member['Name'].isin(['홍길동', '홍길남', '홍길서']),'Name':'Email']

  Name  Age          Email
동  홍길동   20  hong@hong.com
서  홍길서   30   seo@hong.com
남  홍길남   21   nam@hong.com

In [387]:
# 1월생의 데이터 ; Birth datetime dtype 확인 필요
member[member['Birth'].dt.month == 1]

  Name  Age          Email  Address      Birth
동  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
중  홍길중   23   mid@hong.com   부산시 중구 1999-01-30

In [388]:
# 서울에 거주 중인 1월생의 데이터
member[(member['Birth'].dt.month == 1)&(member['Address'].str.startswith('서울'))]

  Name  Age          Email  Address      Birth
동  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01

In [389]:
member = pd.read_csv('data/ch11_member.csv', comment='#', parse_dates=['Birth'])

In [391]:
member.loc[[2,4], 'Email'] = np.nan
member

  Name  Age          Email  Address      Birth
0  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
1  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
2  홍길남   21            NaN  서울시 강동구 1999-11-01
3  홍길북   22   buk@hong.com  서울시 관악구 1999-05-01
4  홍길중   23            NaN   부산시 중구 1999-01-30

In [392]:
# 모든 행과 열의 결측치 여부를 확인
member.isna()

    Name    Age  Email  Address  Birth
0  False  False  False    False  False
1  False  False  False    False  False
2  False  False   True    False  False
3  False  False  False    False  False
4  False  False   True    False  False

In [393]:
# 각 열의 결측치 개수
member.isna().sum(axis=0)

Name       0
Age        0
Email      2
Address    0
Birth      0
dtype: int64

In [395]:
member[member.isna().any(axis=1)]

  Name  Age Email  Address      Birth
2  홍길남   21   NaN  서울시 강동구 1999-11-01
4  홍길중   23   NaN   부산시 중구 1999-01-30

**※ 데이터 프레임의 부분 데이터 조회 방법**
- df[열 이름] : 특정 열의 모든 행 조회
- df[조건] : 조건에 맞는 행의 모든 열 조회
- df.loc[행 이름, 열 이름] : 행 이름과 열 이름으로 조회
    * 조건 조회 가능
    * List, 슬라이싱 가능
    * 열 이름 생략 시 모든 열
- df.iloc[행 번호, 열 번호] : 행 번호와 열 번호로 조회
    * List, 슬라이싱 가능
    * 열 번호 생략 시 모든 열

# 연습문제

In [396]:
import seaborn as sns
iris = sns.load_dataset('iris')
iris.iloc[::25]

     sepal_length  sepal_width  petal_length  petal_width     species
0             5.1          3.5           1.4          0.2      setosa
25            5.0          3.0           1.6          0.2      setosa
50            7.0          3.2           4.7          1.4  versicolor
75            6.6          3.0           4.4          1.4  versicolor
100           6.3          3.3           6.0          2.5   virginica
125           7.2          3.2           6.0          1.8   virginica

In [404]:
# 1. sepal_length 열만 출력

iris['sepal_length']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [408]:
# 2. 0~10행까지 마지막 열을 제외한 데이터 (loc, iloc)

iris.iloc[0:11,:-1]

    sepal_length  sepal_width  petal_length  petal_width
0            5.1          3.5           1.4          0.2
1            4.9          3.0           1.4          0.2
2            4.7          3.2           1.3          0.2
3            4.6          3.1           1.5          0.2
4            5.0          3.6           1.4          0.2
5            5.4          3.9           1.7          0.4
6            4.6          3.4           1.4          0.3
7            5.0          3.4           1.5          0.2
8            4.4          2.9           1.4          0.2
9            4.9          3.1           1.5          0.1
10           5.4          3.7           1.5          0.2

In [409]:
# 2. 0~10행까지 마지막 열을 제외한 데이터 (loc, iloc)

iris.loc[0:10,'sepal_length':'petal_width']

    sepal_length  sepal_width  petal_length  petal_width
0            5.1          3.5           1.4          0.2
1            4.9          3.0           1.4          0.2
2            4.7          3.2           1.3          0.2
3            4.6          3.1           1.5          0.2
4            5.0          3.6           1.4          0.2
5            5.4          3.9           1.7          0.4
6            4.6          3.4           1.4          0.3
7            5.0          3.4           1.5          0.2
8            4.4          2.9           1.4          0.2
9            4.9          3.1           1.5          0.1
10           5.4          3.7           1.5          0.2

In [412]:
# 3. 3~10 행중에 'sepal_length'와 'petal_length' 열만 (loc, iloc)

iris.loc[3:10,['sepal_length','petal_length']]

    sepal_length  petal_length
3            4.6           1.5
4            5.0           1.4
5            5.4           1.7
6            4.6           1.4
7            5.0           1.5
8            4.4           1.4
9            4.9           1.5
10           5.4           1.5

In [411]:
# 3. 3~10 행중에 'sepal_length'와 'petal_length' 열만 (loc, iloc)

iris.iloc[3:10,[0,2]]

   sepal_length  petal_length
3           4.6           1.5
4           5.0           1.4
5           5.4           1.7
6           4.6           1.4
7           5.0           1.5
8           4.4           1.4
9           4.9           1.5

In [423]:
# 4. 0번째, 50번째, 100번째 행의 모든 열 (loc, iloc)

iris.loc[0:100:50]

     sepal_length  sepal_width  petal_length  petal_width     species
0             5.1          3.5           1.4          0.2      setosa
50            7.0          3.2           4.7          1.4  versicolor
100           6.3          3.3           6.0          2.5   virginica

In [415]:
# 4. 0번째, 50번째, 100번째 행의 모든 열 (loc, iloc)

iris.iloc[[0,50,100]]

     sepal_length  sepal_width  petal_length  petal_width     species
0             5.1          3.5           1.4          0.2      setosa
50            7.0          3.2           4.7          1.4  versicolor
100           6.3          3.3           6.0          2.5   virginica

In [425]:
# 5. 0번째, 25, 50번째, 75번, 100번째, 125번째 행의 petal_length와 petal_width (loc, iloc)

iris.loc[0:125:25,['petal_length','petal_width']]

     petal_length  petal_width
0             1.4          0.2
25            1.6          0.2
50            4.7          1.4
75            4.4          1.4
100           6.0          2.5
125           6.0          1.8

In [428]:
# 5. 0번째, 25, 50번째, 75번, 100번째, 125번째 행의 petal_length와 petal_width (loc, iloc)

iris.iloc[0:126:25,[2,3]]

     petal_length  petal_width
0             1.4          0.2
25            1.6          0.2
50            4.7          1.4
75            4.4          1.4
100           6.0          2.5
125           6.0          1.8

In [434]:
# 6. species가 versicolor인 데이터의 모든 열

iris[iris['species'].str.startswith('versicolor')]
iris[iris['species'].str.contains('versicolor')]
iris[iris['species']=='versicolor']

    sepal_length  sepal_width  petal_length  petal_width     species
50           7.0          3.2           4.7          1.4  versicolor
51           6.4          3.2           4.5          1.5  versicolor
52           6.9          3.1           4.9          1.5  versicolor
53           5.5          2.3           4.0          1.3  versicolor
54           6.5          2.8           4.6          1.5  versicolor
55           5.7          2.8           4.5          1.3  versicolor
56           6.3          3.3           4.7          1.6  versicolor
57           4.9          2.4           3.3          1.0  versicolor
58           6.6          2.9           4.6          1.3  versicolor
59           5.2          2.7           3.9          1.4  versicolor
60           5.0          2.0           3.5          1.0  versicolor
61           5.9          3.0           4.2          1.5  versicolor
62           6.0          2.2           4.0          1.0  versicolor
63           6.1          2.9           4.7          1.4  versicolor
64           5.6          2.9           3.6          1.3  versicolor
65           6.7          3.1           4.4          1.4  versicolor
66           5.6          3.0           4.5          1.5  versicolor
67           5.8          2.7           4.1          1.0  versicolor
68           6.2          2.2           4.5          1.5  versicolor
69           5.6          2.5           3.9          1.1  versicolor
70           5.9          3.2           4.8          1.8  versicolor
71           6.1          2.8           4.0          1.3  versicolor
72           6.3          2.5           4.9          1.5  versicolor
73           6.1          2.8           4.7          1.2  versicolor
74           6.4          2.9           4.3          1.3  versicolor
75           6.6          3.0           4.4          1.4  versicolor
76           6.8          2.8           4.8          1.4  versicolor
77           6.7          3.0           5.0          1.7  versicolor
78           6.0          2.9           4.5          1.5  versicolor
79           5.7          2.6           3.5          1.0  versicolor
80           5.5          2.4           3.8          1.1  versicolor
81           5.5          2.4           3.7          1.0  versicolor
82           5.8          2.7           3.9          1.2  versicolor
83           6.0          2.7           5.1          1.6  versicolor
84           5.4          3.0           4.5          1.5  versicolor
85           6.0          3.4           4.5          1.6  versicolor
86           6.7          3.1           4.7          1.5  versicolor
87           6.3          2.3           4.4          1.3  versicolor
88           5.6          3.0           4.1          1.3  versicolor
89           5.5          2.5           4.0          1.3  versicolor
90           5.5          2.6           4.4          1.2  versicolor
91           6.1          3.0           4.6          1.4  versicolor
92           5.8          2.6           4.0          1.2  versicolor
93           5.0          2.3           3.3          1.0  versicolor
94           5.6          2.7           4.2          1.3  versicolor
95           5.7          3.0           4.2          1.2  versicolor
96           5.7          2.9           4.2          1.3  versicolor
97           6.2          2.9           4.3          1.3  versicolor
98           5.1          2.5           3.0          1.1  versicolor
99           5.7          2.8           4.1          1.3  versicolor

In [435]:
# 7. species가 setosa인 데이터 최초 5개 행만 출력

iris[iris['species']=='setosa'].head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [436]:
# 8. sepal_length가 6.5이상인 데이터 최초 5개 행만 출력

iris[iris['sepal_length']>=6.5].head()

    sepal_length  sepal_width  petal_length  petal_width     species
50           7.0          3.2           4.7          1.4  versicolor
52           6.9          3.1           4.9          1.5  versicolor
54           6.5          2.8           4.6          1.5  versicolor
58           6.6          2.9           4.6          1.3  versicolor
65           6.7          3.1           4.4          1.4  versicolor

In [437]:
# 9. sepal_length가 7.2이상인 데이터의 'sepal_length'와 'sepal_width'와 'petal_length'

iris.loc[iris['sepal_length']>=7.2,'sepal_length':'petal_length']

     sepal_length  sepal_width  petal_length
105           7.6          3.0           6.6
107           7.3          2.9           6.3
109           7.2          3.6           6.1
117           7.7          3.8           6.7
118           7.7          2.6           6.9
122           7.7          2.8           6.7
125           7.2          3.2           6.0
129           7.2          3.0           5.8
130           7.4          2.8           6.1
131           7.9          3.8           6.4
135           7.7          3.0           6.1

In [438]:
# 10. versicolor종중에서 sepal_length가 6.5보다 큰 데이터의 모든 열
iris[(iris['species']=='versicolor')&(iris['sepal_length']>6.5)]

    sepal_length  sepal_width  petal_length  petal_width     species
50           7.0          3.2           4.7          1.4  versicolor
52           6.9          3.1           4.9          1.5  versicolor
58           6.6          2.9           4.6          1.3  versicolor
65           6.7          3.1           4.4          1.4  versicolor
75           6.6          3.0           4.4          1.4  versicolor
76           6.8          2.8           4.8          1.4  versicolor
77           6.7          3.0           5.0          1.7  versicolor
86           6.7          3.1           4.7          1.5  versicolor

# 5. 데이터 삭제 및 추가

## 5.1 데이터 프레임의 요소 삭제
- df.drop(label, axis) *label:열 이름 or 행 이름
    - axis=0 : 행 삭제
    - axis=1 : 열 삭제

In [440]:
import pandas as pd
member = pd.read_csv('data/ch11_member.csv', comment='#', parse_dates=['Birth'])
member.index = ['동', '서', '남', '북', '중']
member

  Name  Age          Email  Address      Birth
동  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
서  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
남  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01
북  홍길북   22   buk@hong.com  서울시 관악구 1999-05-01
중  홍길중   23   mid@hong.com   부산시 중구 1999-01-30